name: mail on push 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:

  gmail-send:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: cinotify/github-action@main
        with:
          to: 'example@example.com'
          subject: 'building main'
          body: '<em>This is a notification from GitHub actions.</em>'
          type: 'text/html'
          

