name: send email on push
on:
  push:
    branches:
      - main 

jobs:
  send_email:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Send Email
        uses: cinotify/github-action@main
        with:
          to: "shahar00001@gmail.com"
          subject: " mail when push "
          body: "<em>there was a push to main.</em>"
          type: "text/html"